### ISSUE TITLE
Could not load this plugin

### ISSUE THREAD

**Issue by bittin** [hagabaka/chatzilla-plugins#2]
Got this problem when trying to load the plugin [ERROR] An error occurred extracting the compressed source: [Exception... "Component returned failure code: 0x80520015 (NS_ERROR_FILE_ACCESS_DENIED) [nsILocalFile.remove]"  nsresult: "0x80520015 (NS_ERROR_FILE_ACCESS_DENIED)"  location: "JS frame :: chrome://chatzilla/content/static.js :: cli_installPlugin :: line 3400"  data: no] 

anyone have any idea why or have an updated .zip 

Latest ChatZilla on Windows 8.1

**Comment by hagabaka** [comment]
The zip to use when installing a plugin in ChatZilla should contain the plugin files directly, including `init.js`. The file you downloaded from GitHub has the `channel-tree`directory, and under it the plugin files. That's why you got the error.

Here is a zip I just made which works:

https://www.dropbox.com/s/2adtg3upaal5o5i/channel-tree.zip?dl=1

**Comment by bittin** [comment]
yeah that worked, thank you :) :+1:
